services:

  mxisd-kc:
    image: mxisd-kc:latest
    ports:
     - 80:8091
    environment:
     - CLIENT_ID=${LOCAL_CLIENT_ID}
     - CLIENT_SECRET=${LOCAL_CLIENT_SECRET}
     - KEYCLOAK_URL=${LOCAL_KEYCLOAK_URL}
     - KEYCLOAK_REALM=${LOCAL_KEYCLOAK_REALM}
     - KEYCLOAK_USER=${LOCAL_KEYCLOAK_USER}
     - KEYCLOAK_PASSWORD=${LOCAL_KEYCLOAK_PASSWORD}
     - KEYCLOAK_ATTRIBUTES_VALID_3PIDS=${LOCAL_KEYCLOAK_ATTRIBUTES_VALID_3PIDS}

