name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        id: go_install
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Prepare mxisd-kc
        id: prepare_mxisd-kc
        if: ${{hashFiles('./go.mod') == ''}}
        run: |
          go mod init nia-medtech.com/mxisd-kc
          go mod tidy

      - name: Build mxisd-kc
        id: build_mxisd-kc
        run: go build -o output/backend .

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker-private.nexus.nia-medtech.com/com.niamedtech.3rdparty/mxisd-kc
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: nexus.nia-medtech.com:5000
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
